---
- name: Install Mysql
  become: true
  apt:
    name:
      - python-mysqldb
      - mysql-server
    state: present

- name: Give mysql user a password
  become: true
  mysql_user:
    name: root
    password: "{{mysql_root_password}}"
    login_user: root
    login_password: "{{mysql_root_password}}"
    check_implicit_admin: true

- name: Configure client login via CLI
  template:
    src: templates/my.cnf.j2
    dest: /home/vagrant/.my.cnf
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Create shopware database
  mysql_db:
    name: shopware
    state: present

- name: Remove test database
  mysql_db:
    name: test
    state: absent
