---
- name: Add PHP7 PPA by ondrej
  become: true
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Install PHP by version
  become: true
  apt:
    name:
      - php{{php_version}}-cli
      - php{{php_version}}-fpm
      - php{{php_version}}-curl
      - php{{php_version}}-ctype
      - php{{php_version}}-iconv
      - php{{php_version}}-gd
      - php{{php_version}}-json
      - php{{php_version}}-mbstring
      - php{{php_version}}-xml
      - php{{php_version}}-zip
      - php{{php_version}}-mysql

- name: Set timezone for PHP-FPM to Europe/Berlin
  become: true
  ini_file:
    path: "{{php_fpm_ini_path}}"
    section: Date
    option: date.timezone
    value: Europe/Berlin
  notify: Reload PHP-FPM

- name: Set timezone for PHP-CLI to Europe/Berlin
  become: true
  ini_file:
    path: "{{php_cli_ini_path}}"
    section: Date
    option: date.timezone
    value: Europe/Berlin
